version: '3.8'

services:
  master:
    image: postgres:16
    container_name: master
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./master/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - pg_network

  standby:
    image: postgres:16
    container_name: standby
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - master
    volumes:
      - ./standby/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./standby/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./standby/init.sh:/docker-entrypoint-initdb.d/init_standby.sh
    command: >
      bash /docker-entrypoint-initdb.d/init_standby.sh
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
